name: "Windows CI"
on:
  push:
    branches:
      - '**'
  release:
    types: [published]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '>=3.1.18'
          version: '6.8.0'
          target: 'desktop'
          cache: true
          arch: 'win64_msvc2022_64'
          modules: 'qt3d qtcharts qtconnectivity qtdatavis3d qtgraphs qtgrpc qthttpserver qtimageformats qtlanguageserver qtlocation qtlottie qtmultimedia qtnetworkauth qtpositioning qtquick3dphysics qtquickeffectmaker qtremoteobjects qtscxml qtsensors qtserialbus qtserialport qtspeech qtvirtualkeyboard qtwebchannel qtwebsockets qtwebview qt5compat qtquick3d qtquicktimeline qtshadertools'
      - name: Install QCoro
        uses: theCheeseboard/actions/build-cmake-project@actions
        with:
          project: danvratil/qcoro
          commitish: v0.10.0
      - name: Install libcontemporary
        uses: theCheeseboard/actions/build-cmake-project@actions
        with:
          project: theCheeseboard/libcontemporary
          commitish: features/qml
      - name: Install contemporary-qml
        id: contemporaryqml
        uses: theCheeseboard/actions/build-cmake-project@actions
        with:
          project: .
          commitish: .
          extra-cmake-args: -DBUILD_PLAYGROUND=ON
      - name: Deploy contemporary-qml
        env:
          SOURCE_DIRECTORY: ${{ steps.contemporaryqml.outputs.source-directory }}
          BUILD_DIRECTORY: ${{ steps.contemporaryqml.outputs.build-directory }}
          INSTALL_DIRECTORY: ${{ steps.contemporaryqml.outputs.install-directory }}
        run: |
          New-Item -ItemType Directory -Force -Path output
          $executable = Move-Item -Path "$env:BUILD_DIRECTORY/playground/contemporary*.exe" -Destination output -Force -PassThru
          windeployqt output --qmldir="$env:SOURCE_DIRECTORY" -printsupport
          copy $env:INSTALL_DIRECTORY/bin/*.dll output
      - name: Upload contemporary-qml artifact
        uses: actions/upload-artifact@v4
        with:
          name: contemporary-qml-win
          path: output
